# Generated by Django 3.1 on 2022-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='parent',
        ),
        migrations.AddField(
            model_name='company',
            name='KRS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='NIP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Regon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contactPerson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hireType',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('temp-to-temp', 'Temp-to_Temp'), ('outsourcing', 'Outsourcing'), ('leasing', 'Leasing')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='numberOfWorkers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='payAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
