# Generated by Django 3.1 on 2022-09-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20220907_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not decided', 'Not decided')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=150)),
                ('citizenship', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='employees')),
                ('education', models.CharField(blank=True, choices=[('none', 'None'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('higher', 'Higher'), ('bachelor', 'Bachelor'), ('master', 'Master')], max_length=50, null=True)),
                ('pesel', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_id', models.CharField(blank=True, max_length=50, null=True)),
                ('karta_pobytu', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_entry_to_poland', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='employer.company')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
